---
output: html_document
---

<!-- The following script makes it possible to use the mhchem -->
<!-- latex package in a .Rmd file and to knit it into an .html file -->
<!-- the font size is scaled to 90% to match text -->

```{=html}
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: {
    extensions: ["[Contrib]/mhchem/mhchem.js"]
}
});
MathJax.Hub.Config({ 
        "HTML-CSS": { scale: 90 }, 
        SVG: { linebreaks: { automatic:true } }, 
 });
</script>
```

<!-- text for activity 2 -->

The current in a chronoamperometry experiment is given by the Cottrell equation
$$i(t) = \frac{n F A C \sqrt{D}}{\sqrt{\pi}\sqrt{t}}$$
where $i(t)$ is the current at a time, $t$, after the pulse is applied, $n$ is the number of electrons in the redox reaction, $A$ is the area of the electrode in cm^2^, $D$ is the diffusion coefficient for the electroactive species (Ox or Red) in cm^2^/s and $C$ is its concentration in mol/L, and $F$ is Faraday's constant (96,458 C/mol, where C is a coulomb).

**Exercise 1**. Explain why an increase in $n$, $A$, $D$, and $C$ results in a larger current, but an increase in $t$ results in a smaller current.

**Exercise 2**. Use the radio buttons for $n$, $A$, $D$, and $C$ to verify that the relationship between $i(t)$ and $n$, $A$, and $C$ is linear, but that there is a square-root relationship between $i(t)$ and $D$, and an inverse square-root relationship between $i(t)$ and $t$.

**Exercise 3**. Current is measured in amperes (A), which is equivalent to coulombs per second; that is, 1 C/s = 1 A. Show that the units on the right side of the Cottrell equation yield a current in amperes; focus on the units and do not use specific numerical values for any of the variables. Although we usually report concentration in mol/L---as this is the most common way that we report concentration in the lab---for this exercise you need to express volume using units of mol/cm^3^. Why? 

**Exercise 4**. Set the radio buttons to $n = 1$, $A = 0.01 \text{ cm}^2$, $D = 1\times10^{-5} \text{ cm}^2\text{/s}$, and $C = 0.001 \text{ mol/L}$, and make note of the current in µA at a total elapsed time of 14 s. Verify that this current is correct by using the Cottrell equation to calculate the current. Be sure to consider your work on Exercise 3 and to consider the meaning of time in the Cottrell equation.

**Exercise 5**. Explain how you can use the Cottrell equation to determine the concentration of an analyte in a sample.
